# Generated by Django 5.0.6 on 2024-06-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VRPInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("clients", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("distance", models.IntegerField()),
            ],
        ),
    ]
