# Generated by Django 5.0.6 on 2025-04-13 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vrp", "0004_table_benchmark_cost_solution"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstrategiaExperimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "algoritmo",
                    models.CharField(
                        choices=[
                            ("AG", "Algoritmo Genético"),
                            ("ACO", "ACO"),
                            ("HIBRIDO", "Híbrido"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracionExperimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("population_size", models.IntegerField(blank=True, null=True)),
                ("num_generations", models.IntegerField(blank=True, null=True)),
                ("mutation_rate", models.FloatField(blank=True, null=True)),
                ("use_elitism", models.BooleanField(blank=True, null=True)),
                ("num_ants", models.IntegerField(blank=True, null=True)),
                ("max_iter", models.IntegerField(blank=True, null=True)),
                ("alpha", models.FloatField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("evaporation_rate", models.FloatField(blank=True, null=True)),
                ("usar_2opt", models.BooleanField(default=False)),
                ("reinicio", models.BooleanField(default=False)),
                ("hibridacion", models.BooleanField(default=False)),
                ("poblacion_desde_aco", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "instancia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vrp.vrpinstance",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vrp.estrategiaexperimento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoRepeticion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iteracion", models.IntegerField()),
                ("costo_obtenido", models.FloatField()),
                ("tiempo_ejecucion", models.FloatField()),
                ("gap_porcentual", models.FloatField(blank=True, null=True)),
                ("costo_optimo", models.FloatField(blank=True, null=True)),
                ("iteracion_mejora", models.IntegerField(blank=True, null=True)),
                ("mejor_ruta", models.JSONField(blank=True, null=True)),
                ("path_imagen_solucion", models.CharField(blank=True, max_length=255)),
                (
                    "configuracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vrp.configuracionexperimento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumenExperimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promedio_costo", models.FloatField()),
                ("promedio_gap", models.FloatField()),
                ("tiempo_total", models.FloatField()),
                ("mejor_resultado", models.FloatField()),
                ("desviacion_estandar", models.FloatField()),
                (
                    "configuracion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vrp.configuracionexperimento",
                    ),
                ),
            ],
        ),
    ]
