# Generated by Django 5.0.6 on 2025-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vrp", "0005_estrategiaexperimento_configuracionexperimento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configuracionexperimento",
            old_name="usar_2opt",
            new_name="reinicio_adaptativo",
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="ajuste_dinamico",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="estrategia_2opt",
            field=models.CharField(
                choices=[
                    ("NO_2OPT", "No aplicar"),
                    ("EACH_GEN", "Cada hijo (AG)"),
                    ("GEN_X", "Cada N generaciones (AG)"),
                    ("TOP_GEN", "Top de la generación (AG)"),
                    ("FINAL", "Solo al final (AG/ACO)"),
                    ("ALL", "Todas las hormigas (ACO)"),
                    ("STUCK", "Si se estanca (ACO)"),
                    ("LAST", "Ultima hormiga (ACO)"),
                ],
                default="NO_2OPT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="exportar_poblacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="freq_2opt",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="restriccion_nodos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="tipo_mutacion",
            field=models.CharField(
                choices=[
                    ("inversion", "Inversión"),
                    ("swap_sequence", "Intercambio de Secuencias"),
                ],
                default="inversion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="configuracionexperimento",
            name="usar_swap",
            field=models.BooleanField(default=False),
        ),
    ]
