# Generated by Django 5.0.6 on 2025-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vrp",
            "0006_rename_usar_2opt_configuracionexperimento_reinicio_adaptativo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vrpinstance",
            name="name_model",
        ),
        migrations.AlterField(
            model_name="vrpinstance",
            name="mutation_rate",
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name="vrpinstance",
            name="num_generations",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vrpinstance",
            name="population_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vrpinstance",
            name="use_elitism",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
